
version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: site
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: userPass
    ports:
      - "5432:5432"
  app:
    build: .
    environment:
      DATABASE_URL: postgres://admin:userPass@db:5432/site
    depends_on:
      - db